export const ROW = 1;
export const COLUMN = 20;
export const PRIMARY_DIAGONAL = 21;
export const SECONDARY_DIAGONAL = 19;

export const LOCAL_API = ' http://localhost:4500'
export const HOST_API = 'https://caro-1612334-api.herokuapp.com'

export const ADD_ITEM = 'ADD_ITEM';
export const RESET = 'RESET';
export const MODIFIED_HISTORY = 'MODIFIED_HISTORY';

export const LOGIN_SUCESS = "LOGIN_SUCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_PENDING = "LOGIN_PENDING";
export const LOGOUT = "LOGOUT";

export const REGISTER_SUCESS = "REGISTER_SUCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const REGISTER_PENDING = "REGISTER_PENDING";

export const GET_INFOMATION = "GET_INFOMATION";
export const GET_INFOMATION_PENDING = "GET_INFOMATION_PENDING";
export const GET_INFOMATION_SUCESS = "GET_INFOMATION_SUCESS";
export const GET_INFOMATION_FAILURE = "GET_INFOMATION_FAILURE";

export const CHANGE_PASSWORD_PENDING = "CHANGE_PASSWORD_PENDING";
export const CHANGE_PASSWORD_SUCESS = "CHANGE_PASSWORD_SUCESS";
export const CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE";